helpdesk/urls.py
"""
django-helpdesk - A Django powered ticket tracker for small enterprise.

(c) Copyright 2008 Jutda. All Rights Reserved. See LICENSE for details.

urls.py - Mapping of URL's to our various views. Note we always used NAMED
          views for simplicity in linking later on.
"""

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from helpdesk.decorators import helpdesk_staff_member_required, protect_view
from helpdesk import settings as helpdesk_settings
from helpdesk.views import feeds, staff, public, kb, login
try:
    # TODO: why is it imported? due to some side-effect or by mistake?
    import helpdesk.tasks  # NOQA
except ImportError:
    pass


class DirectTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        if self.extra_context is not None:
            for key, value in self.extra_context.items():
                if callable(value):
                    context[key] = value()
                else:
                    context[key] = value
        return context


app_name = 'helpdesk'

base64_pattern = r'(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'

urlpatterns = [
    url(r'^dashboard/$',
        staff.dashboard,
        name='dashboard'),

    url(r'^tickets/$',
        staff.ticket_list,
        name='list'),

    url(r'^tickets/update/$',
        staff.mass_update,
        name='mass_update'),

    url(r'^tickets/merge$',
        staff.merge_tickets,
        name='merge_tickets'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/$',
        staff.view_ticket,
        name='view'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_edit/(?P<followup_id>[0-9]+)/$',
        staff.followup_edit,
        name='followup_edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_delete/(?P<followup_id>[0-9]+)/$',
        staff.followup_delete,
        name='followup_delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/edit/$',
        staff.edit_ticket,
        name='edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/update/$',
        staff.update_ticket,
        name='update'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/delete/$',
        staff.delete_ticket,
        name='delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/hold/$',
        staff.hold_ticket,
        name='hold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/unhold/$',
        staff.unhold_ticket,
        name='unhold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/$',
        staff.ticket_cc,
        name='ticket_cc'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/add/$',
        staff.ticket_cc_add,
        name='ticket_cc_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/delete/(?P<cc_id>[0-9]+)/$',
        staff.ticket_cc_del,
        name='ticket_cc_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/add/$',
        staff.ticket_dependency_add,
        name='ticket_dependency_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/delete/(?P<dependency_id>[0-9]+)/$',
        staff.ticket_dependency_del,
        name='ticket_dependency_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/attachment_delete/(?P<attachment_id>[0-9]+)/$',
        staff.attachment_del,
        name='attachment_del'),

    url(r'^raw/(?P<type>\w+)/$',
        staff.raw_details,
        name='raw'),

    url(r'^rss/$',
        staff.rss_list,
        name='rss_index'),

    url(r'^reports/$',
        staff.report_index,
        name='report_index'),

    url(r'^reports/(?P<report>\w+)/$',
        staff.run_report,
        name='run_report'),

    url(r'^save_query/$',
        staff.save_query,
        name='savequery'),

    url(r'^delete_query/(?P<id>[0-9]+)/$',
        staff.delete_saved_query,
        name='delete_query'),

    url(r'^settings/$',
        staff.EditUserSettingsView.as_view(),
        name='user_settings'),

    url(r'^ignore/$',
        staff.email_ignore,
        name='email_ignore'),

    url(r'^ignore/add/$',
        staff.email_ignore_add,
        name='email_ignore_add'),

    url(r'^ignore/delete/(?P<id>[0-9]+)/$',
        staff.email_ignore_del,
        name='email_ignore_del'),

    url(r'^datatables_ticket_list/(?P<query>{})$'.format(base64_pattern),
        staff.datatables_ticket_list,
        name="datatables_ticket_list"),

    url(r'^timeline_ticket_list/(?P<query>{})$'.format(base64_pattern),
        staff.timeline_ticket_list,
        name="timeline_ticket_list"),

]

urlpatterns += [
    url(r'^$',
        protect_view(public.Homepage.as_view()),
        name='home'),

    url(r'^tickets/submit/$',
        public.create_ticket,
        name='submit'),

    url(r'^tickets/submit_iframe/$',
        public.CreateTicketIframeView.as_view(),
        name='submit_iframe'),

    url(r'^tickets/success_iframe/$',  # Ticket was submitted successfully
        public.SuccessIframeView.as_view(),
        name='success_iframe'),

    url(r'^view/$',
        public.view_ticket,
        name='public_view'),

    url(r'^change_language/$',
        public.change_language,
        name='public_change_language'),
]

urlpatterns += [
    url(r'^rss/user/(?P<user_name>[^/]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByUser()),
        name='rss_user'),

    url(r'^rss/user/(?P<user_name>[^/]+)/(?P<queue_slug>[A-Za-z0-9_-]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByUser()),
        name='rss_user_queue'),

    url(r'^rss/queue/(?P<queue_slug>[A-Za-z0-9_-]+)/$',
        helpdesk_staff_member_required(feeds.OpenTicketsByQueue()),
        name='rss_queue'),

    url(r'^rss/unassigned/$',
        helpdesk_staff_member_required(feeds.UnassignedTickets()),
        name='rss_unassigned'),

    url(r'^rss/recent_activity/$',
        helpdesk_staff_member_required(feeds.RecentFollowUps()),
        name='rss_activity'),
]


urlpatterns += [
    url(r'^login/$',
        login.login,
        name='login'),

    url(r'^logout/$',
        auth_views.LogoutView.as_view(
            template_name='helpdesk/registration/login.html',
            next_page='../'),
        name='logout'),

    url(r'^password_change/$',
        auth_views.PasswordChangeView.as_view(
            template_name='helpdesk/registration/change_password.html',
            success_url='./done'),
        name='password_change'),

    url(r'^password_change/done$',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='helpdesk/registration/change_password_done.html',),
        name='password_change_done'),
]

if helpdesk_settings.HELPDESK_KB_ENABLED:
    urlpatterns += [
        url(r'^kb/$',
            kb.index,
            name='kb_index'),

        url(r'^kb/(?P<slug>[A-Za-z0-9_-]+)/$',
            kb.category,
            name='kb_category'),

        url(r'^kb/(?P<item>[0-9]+)/vote/$',
            kb.vote,
            name='kb_vote'),

        url(r'^kb_iframe/(?P<slug>[A-Za-z0-9_-]+)/$',
            kb.category_iframe,
            name='kb_category_iframe'),
    ]

urlpatterns += [
    url(r'^help/context/$',
        TemplateView.as_view(template_name='helpdesk/help_context.html'),
        name='help_context'),

    url(r'^system_settings/$',
        login_required(DirectTemplateView.as_view(template_name='helpdesk/system_settings.html')),
        name='system_settings'),
]

helpdesk/templates/helpdesk/attribution.html
{% load i18n %}
<!-- Sticky Footer -->
<footer class="sticky-footer">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Powered by {% trans "<a href='https://github.com/django-helpdesk/django-helpdesk'>django-helpdesk</a>." %}</span>
        </div>
    </div>
</footer>

helpdesk/templates/helpdesk/edit_ticket.html
{% extends "helpdesk/base.html" %}

{% load i18n bootstrap4form %}

{% block helpdesk_title %}{% trans "Edit Ticket" %}{% endblock %}

{% block helpdesk_breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'helpdesk:list' %}">{% trans "Tickets" %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'helpdesk:list' %}{{ ticket.id }}/">{{ ticket.queue.slug }}-{{ ticket.id }}</a>
    </li>
    <li class="breadcrumb-item active">{% trans "Edit Ticket" %}</li>
{% endblock %}

{% block helpdesk_body %}
    <div class="col-xs-6">
        <div class="panel panel-default">
            <div class="panel-body"><h2>{% trans "Edit a Ticket" %}</h2>
                <p>
                    {% trans "Unless otherwise stated, all fields are required." %}
                    {% trans "Please provide as descriptive a title and description as possible." %}
                </p>
                <p>
                    <strong>{% trans "Note" %}:</strong>
                    {% blocktrans %}Editing a ticket does <em>not</em> send an e-mail to the ticket owner or submitter. No new details should be entered, this form should only be used to fix incorrect details or clean up the submission.{% endblocktrans %}
                </p>
                {% if errors %}<p class="text-danger">{% for error in errors %}{% trans "Error: " %}{{ error }}<br>{% endfor %}</p>{% endif %}
                <form method='post'>
                    {% csrf_token %}
                    <fieldset>
                        {{ form|bootstrap4form }}
                        <div class='buttons form-group'>
                            <input type='submit' class="btn btn-primary btn-sm" value='{% trans "Save Changes" %}'/>
                            <a href='{{ ticket.get_absolute_url }}'>
                                <button class="btn btn-danger">{% trans "Cancel Changes" %}</button>
                            </a>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block helpdesk_js %}
    {{ form.media.js }}
{% endblock %}

helpdesk/templates/helpdesk/kb_category.html
{% extends "helpdesk/public_base.html" %}
{% load i18n %}

{% block helpdesk_title %}{% blocktrans with category.title as kbcat %}{{ kbcat }}{% endblocktrans %}{% endblock %}

{% block helpdesk_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'helpdesk:kb_index' %}">{% trans "Knowledgebase" %}</a>
</li>
<li class="breadcrumb-item active">{% blocktrans with category.title as kbcat %}{{ kbcat }}{% endblocktrans %}</li>
{% endblock %}

{% block helpdesk_body %}
{% include 'helpdesk/kb_category_base.html' %}
</div>

{% endblock %}

helpdesk/templates/helpdesk/navigation-sidebar.html
{% load i18n helpdesk_staff %}

    <!-- Sidebar -->
    <ul class="sidebar navbar-nav">
    {% if helpdesk_settings.HELPDESK_NAVIGATION_ENABLED and user.is_authenticated or user|is_helpdesk_staff %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'helpdesk:dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>{% trans "Dashboard" %}</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:list' %}">
            <i class="fas fa-fw fa-tasks"></i>
            <span>{% trans "All Tickets" %}</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="ticketsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-fw fa-search"></i>
            <span>{% trans "Saved Queries" %}</span>
          </a>
          <div class="dropdown-menu" aria-labelledby="ticketsDropdown">
            {% if user_saved_queries_ %}
            {% for q in user_saved_queries_ %}
            <a class="dropdown-item small" href="{% url 'helpdesk:list' %}?saved_query={{ q.id }}">{{ q.title }}
                {% if q.shared %}
                (Shared{% ifnotequal user q.user %} by {{ q.user.get_username }}{% endifnotequal %})
                {% endif %}
            </a>
            {% endfor %}
            {% else %}
            <p class="dropdown-item small text-wrap">{% trans "No saved queries currently available. You can create one in the All Tickets page." %}</p>
            {% endif %}
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:submit' %}">
            <i class="fas fa-fw fa-plus-circle"></i>
            <span>{% trans "New Ticket" %}</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:report_index' %}">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>{% trans "Reports" %}</span>
          </a>
        </li>
        {% if helpdesk_settings.HELPDESK_KB_ENABLED %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:kb_index' %}">
            <i class="fas fa-fw fa-database"></i>
            <span>{% trans "Knowledgebase" %}</span>
          </a>
        </li>
        {% endif %}
    {% else %}
        {# Public menu #}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'helpdesk:home' %}">
            <i class="fas fa-fw fa-home"></i>
            <span>{% trans "Homepage" %}</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:submit' %}">
            <i class="fas fa-fw fa-plus-circle"></i>
            <span>{% trans "New Ticket" %}</span>
          </a>
        </li>
        {% if helpdesk_settings.HELPDESK_KB_ENABLED %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'helpdesk:kb_index' %}">
            <i class="fas fa-fw fa-database"></i>
            <span>{% trans "Knowledgebase" %}</span>
          </a>
        </li>
        {% endif %}
    {% endif %}
    </ul>

helpdesk/templates/helpdesk/public_homepage.html
{% extends "helpdesk/public_base.html" %}
{% load i18n bootstrap4form %}

{% block helpdesk_title %}{% trans "Welcome to Helpdesk" %}{% endblock %}

{% block helpdesk_breadcrumb %}
    <li class="breadcrumb-item">
        <a href="#">Public</a>
    </li>
    <li class="breadcrumb-item active">Homepage</li>
{% endblock %}

{% block helpdesk_body %}
    <div class="container-fluid">
        <div class="row">
            {% if kb_categories %}
                <div class="col-sm">
                    <h2>{% trans "Knowledgebase Articles" %}</h2>
                    {% for category in kb_categories %}
                        <div class="card" style="margin-top: 15px">
                            <div class="card-body">
                                <h5 class="card-title">{{ category.title }}</h5>
                                <p class="card-text">{{ category.description }}</p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        <a href='{{ category.get_absolute_url }}'>
                                            {% trans 'View articles' %} <i class="fa fa-arrow-right"></i>
                                        </a>
                                    </small>
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <div class="col-sm">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h2>{% trans "Submit a Ticket" %}</h2>
                        {% include 'helpdesk/public_create_ticket_base.html' %}
                    </div>
                </div>
            </div>

            {% if not helpdesk_settings.HELPDESK_VIEW_A_TICKET_PUBLIC and not helpdesk_settings.HELPDESK_SUBMIT_A_TICKET_PUBLIC %}
                <h2>{% trans "Please use button at upper right to login first." %}</h2>
            {% endif %}

            {% if helpdesk_settings.HELPDESK_VIEW_A_TICKET_PUBLIC %}
                <div class="col-sm">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h2>{% trans "View a Ticket" %}</h2>
                            <form method='get' action="{% url 'helpdesk:public_view' %}">
                                <fieldset>
                                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                                        <label for='id_ticket'>{% trans "Ticket" %}</label>
                                        <div class="input-group">
                                            <input type='text' name='ticket' class='form-control'/>
                                        </div>
                                    </div>
                                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                                        <label for='id_email'>{% trans "Your E-mail Address" %}</label>
                                        <div class="input-group">
                                            <input type='text' name='email' class='form-control'/>
                                        </div>
                                    </div>
                                    <div class='buttons form-group'>
                                        <input type='submit' class="btn btn-primary" value='{% trans "View Ticket" %}'/>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block helpdesk_js %}
    {{ form.media.js }}
{% endblock %}

helpdesk/templates/helpdesk/report_output.html
{% extends "helpdesk/base.html" %}{% load i18n %}
{% load static %}

{% block helpdesk_title %}{% trans "Reports &amp; Statistics" %}{% endblock %}

{% block helpdesk_head %}

{% endblock %}

{% block helpdesk_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'helpdesk:report_index' %}">{% trans "Reports &amp; Statistics" %}</a>
</li>
<li class="breadcrumb-item active">{{ title }}</li>
{% endblock %}

{% block helpdesk_body %}
<h2>{% trans "Reports &amp; Statistics" %}</h2>

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-filter"></i>
        {% trans 'Saved Queries' %}
    </div>
    <div class="card-body">
        {% if user_saved_queries_ %}
            <p>{% trans "You can run this query on filtered data by using one of your saved queries." %}</p>
            <form method='GET' action='./'>
                <label for='saved_query'>{% trans "Select Query:" %}</label>
                <select name='saved_query'>
                    <option value="">--------</option>{% for q in user_saved_queries_ %}
                    <option value="{{ q.id }}"{% ifequal saved_query q %} selected{% endifequal %}>{{ q.title }}</option>{% endfor %}
                </select>
                <input class="btn btn-primary" type='submit' value='{% trans "Filter Report" %}'>
            </form>
        {% else %}
            <p>{% trans "Want to filter this report to just show a subset of data? Go to the Ticket List, filter your query, and save your query." %}</p>
        {% endif %}
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-chart-line"></i>
        {{ title }}
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>{% for h in headings %}
                        <th>{% if forloop.first %}{{ h|title }}{% else %}{{ h }}{% endif %}</th>{% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for d in data %}
                    <tr class='row_{% cycle 'odd' 'even' %}'>
                        {% for f in d %}<td class='report'>{{ f }}</td>{% endfor %}
                    </tr>
                    {% endfor %}
                    <tr>
                        {% for f in total_data %}<td class='report'>{{ f }}</td>{% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
        <div class="flot-chart">
            <div class="flot-chart-content" id="chart-content"></div>
        </div>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->
{% endblock %}


{% block helpdesk_js %}

    <!-- Flot Charts JavaScript -->
    <script src="/static/helpdesk/vendor/flot/excanvas.min.js"></script>
    <script src="/static/helpdesk/vendor/flot/jquery.flot.js"></script>
    <script src="/static/helpdesk/vendor/flot/jquery.flot.categories.js"></script>
    <script src="/static/helpdesk/vendor/flot/jquery.flot.pie.js"></script>
    <script src="/static/helpdesk/vendor/flot/jquery.flot.resize.js"></script>
    <script src="/static/helpdesk/vendor/flot/jquery.flot.time.js"></script>
    <script src="/static/helpdesk/vendor/flot-tooltip/jquery.flot.tooltip.min.js"></script>

    <!-- Morris Charts JavaScript -->
    {% if helpdesk_settings.HELPDESK_USE_CDN %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    {% else %}
    <script src="{% static 'helpdesk/vendor/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'helpdesk/vendor/morrisjs/morris.min.js' %}"></script>
    {% endif %}

{% if charttype == "date" %}
<script type='text/javascript'>

Morris.Line({
  element: 'chart-content',
  data: {% autoescape on %}{{ morrisjs_data|safe }}{% endautoescape %},
  xkey: 'x',
  ykeys: [{% for d in data %}{{ forloop.counter0 }}{% if not forloop.last %}, {% endif %}{% endfor %}],
  labels: [{% for n in series_names %}"{{ n }}"{% if not forloop.last %}, {% endif %}{% endfor %}],
  xLabels: "month"
});

</script>
{% endif %}
{% if charttype == "bar" %}
<script type='text/javascript'>

Morris.Bar({
  element: 'chart-content',
  data: {% autoescape on %}{{ morrisjs_data|safe }}{% endautoescape %},
  xkey: 'x',
  ykeys: [{% for d in data %}{{ forloop.counter0 }}{% if not forloop.last %}, {% endif %}{% endfor %}],
  labels: [{% for n in series_names %}"{{ n }}"{% if not forloop.last %}, {% endif %}{% endfor %}]
});

</script>
{% endif %}



{% endblock %}

helpdesk/templates/helpdesk/success_iframe.html
{% load i18n %}
<h1>
{% trans "Ticket submitted successfully! We will reply via email as soon as we get the chance." %}
</h1>

helpdesk/templates/helpdesk/ticket_cc_list.html
{% extends "helpdesk/base.html" %}

{% load i18n %}

{% block helpdesk_title %}{% trans "Ticket CC Settings" %}{% endblock %}

{% block helpdesk_breadcrumb %}
    <li class="breadcrumb-item">
        <a href="{% url 'helpdesk:list' %}">{% trans "Tickets" %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'helpdesk:list' %}{{ ticket.id }}/">{{ ticket.queue.slug }}-{{ ticket.id }}</a>
    </li>
    <li class="breadcrumb-item active">{% trans "CC Settings" %}</li>
{% endblock %}

{% block helpdesk_body %}{% blocktrans with ticket.title as ticket_title and ticket.id as ticket_id %}
<h2>Ticket CC Settings</h2>

<p>The following people will receive an e-mail whenever <em><a href='../'>{{ ticket_title }}</a></em> is updated. Some people can also view or edit the ticket via the public ticket views.</p>

<p>You can add a new recipient to the list or delete any of the items below as required.</p>{% endblocktrans %}

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    {% trans "Ticket CC List" %}
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div><a href='add/'><button class="btn btn-success btn-sm"><i class="fa fa-plus-circle"></i>{% trans "Add an Email or Helpdesk User" %}</button></a></div>
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>{% trans "E-Mail Address or Helpdesk User" %}</th>
                                    <th class="text-center">{% trans "View?" %}</th>
                                    <th class="text-center">{% trans "Update?" %}</th>
                                    <th class="text-center">{% trans "Delete" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for person in copies_to %}
                                    <tr class='row_{% cycle 'odd' 'even' %}'>
                                        <td>{{ person.display }}</td>
                                        <td class="text-center">
                                            {% if person.can_view %}
                                                <i class="fa fa-2x fa-check text-success"></i>
                                            {% else %}
                                                <i class="fa fa-2x fa-times text-danger"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            {% if person.can_update %}
                                                <i class="fa fa-2x fa-check text-success"></i>
                                            {% else %}
                                                <i class="fa fa-2x fa-times text-danger"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            <a href='{% url 'helpdesk:ticket_cc_del' ticket.id person.id %}'>
                                                <button class="btn btn-danger btn-xs">
                                                    {% trans "Delete" %}
                                                </button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <p>
        <a href='{% url 'helpdesk:view' ticket.id %}'>
            <button class="btn btn-primary btn-lg">
                {% blocktrans with ticket.title as ticket_title %}Return to <em>{{ ticket_title }}</em>{% endblocktrans %}
            </button>
        </a>
    </p>

{% endblock %}

helpdesk/templates/helpdesk/user_settings.html
{% extends "helpdesk/base.html" %}{% load i18n bootstrap4form %}

{% block helpdesk_title %}{% trans "Change User Settings" %}{% endblock %}

{% block helpdesk_breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'helpdesk:user_settings' %}">{% trans "Settings" %}</a>
</li>
<li class="breadcrumb-item active">
    Change User Settings
</li>
{% endblock %}

{% block helpdesk_body %}
<h2>{% trans "User Settings" %}</h2>

<p>{% blocktrans %}Use the following options to change the way your helpdesk system works for you. These settings do not impact any other user.{% endblocktrans %}</p>

{% block form_content %}
<form role="form" method='post' action='./'>
    {% csrf_token %}
    {{ form|bootstrap4form }}
    <div class="form-group">
      <input type="submit" value="Submit"/>
    </div>
</form>
{% endblock %}

{% endblock %}